export const PROJECT_TECH_ICON_MAP = {
  TypeScript: "/icons/tech/TypeScript.svg",
  JavaScript: "/icons/tech/JavaScript.svg",
  React: "/icons/tech/React.svg",
  ReactNative: "/icons/tech/ReactNative.png",
  ReactQuery: "/icons/tech/ReactQuery.svg",
  Redux: "/icons/tech/Redux.svg",
  Recoil: "/icons/tech/Recoil.svg",
  Axios: "/icons/tech/Axios.svg",
  MSW: "/icons/tech/MSW.png",
  Firebase: "/icons/tech/Firebase.svg",
  Vite: "/icons/tech/Vite.svg",
  Vercel: "/icons/tech/Vercel.svg",
  Sass: "/icons/tech/Sass.svg",
  CSS: "/icons/tech/CSS.svg",
  TailwindCSS: "/icons/tech/TailwindCSS.svg",
  Expo: "/icons/tech/expo.svg",
  GitHub: "/icons/tech/GitHub.svg",
  ReactHookForm: "/icons/tech/ReactHookForm.png",
};
